### PR TITLE
Allowing users to override Mongo's collection and port

### PR DESCRIPTION
**Pull request by arosequist**

### CODE REVIEW

**Comment by lgaticaq** [comment]
Hello thanks for the PR, but is not necessary. With the `MONGODB URI` is possible set all options (ip, port, collection, user and password). Example `mongodb://user:pass@host:port/collectionName`
In which case you could not set the collection and port?

**Comment by arosequist** [comment]
The port is able to be set that way, but I don't know how to pass in the collection. I think the syntax for mongo connections is `mongodb://user:pass@host:port/databaseName`.

**Comment by lgaticaq** [comment]
You're right, I confused the name of the database with the name of the collection.

**Comment by lgaticaq** [comment]
The new version is pushed with tags latest and 0.4.0 (some version of agendash). Thanks

**Pull request merged**
